Provide a non-threadsafe mechanism to override registered values
mlibrary/closet pull request #9
Opened 2023-10-23 21:01 UTC by billdueber

Uses a simple push/pop with the current context (registry, cache, etc.) to override withing the push/pop cycle, or use `container.override { ...  } ` to automatically push/pop at the beginning and end of the block.

Did I say "non-threadsafe?" OVERRIDES ARE NOT THREADSAFE!

2023-10-24 22:11 UTC, billdueber commented
Geez. Realized I didn't commit a couple files. Fixed.

2023-10-26 19:09 UTC, aelkiss reviewed
This looks pretty nice; I want to give it a try with some of my projects where I override things in tests to make sure that it works as expected.

2023-11-09 03:30 UTC, moseshll commented
Spent a bit of time with this branch and `hathitrust_catalog_indexer` and overall I'm liking it. There is some behavior in this branch that I believe violates the principle of least astonishment, however. To wit:
```
irb(main):002:0> c = Canister.new                                                    
irb(main):003:0> c.push_context!                                               
irb(main):004:0> c.register(:a) { "b" }                                                                         
irb(main):005:0> c.pop_context!                                                                          
irb(main):006:0> c[:a]
=> "b"
```
Expected behavior would, for me, be a raised exception since the registration was made in a pushed context.
`@context.dup` defaults to a shallow copy of the existing context, so the `@registry` hash is shared between all contexts. I tried this and was satisfied with the behavior:

```
def dup
  self.class.new(registry: @registry.dup)
end
```

(I should also note that doing `c[:some_key_i_havent_registered_yet]` leaves junk on the `@stack` but that's an issue for another day.)

2023-11-09 03:41 UTC, moseshll requested changes
See main comment. (Figured I might as well turn this into a real review.)

_Probable Scope Creep Initiate!_
I also find the cited behavior of e.g., `c[:some_key_i_havent_registered_yet]` (raising `NoMethodError` and leaving junk on the stack) somewhat jarring. Surely we can act more like `Hash` (which is ultimately how I conceptualize this class) or at least return a more appropriate exception class.

2025-03-20 16:03 UTC, billdueber commented
Closing this as unworkable in its current form. Will add something different soon.

2025-03-20 16:03 UTC, closed without merging